### ISSUE TITLE
My server doesn't start !

### ISSUE THREAD

**Issue by Rix565** [jkutner/heroku-buildpack-minecraft#73]
```
2021-03-23T18:02:17.882604+00:00 heroku[web.1]: State changed from up to down
2021-03-23T18:02:17.897907+00:00 heroku[web.1]: Idling because quota is exhausted
2021-03-23T18:02:17.000000+00:00 app[api]: Build succeeded
2021-03-23T18:02:18.797007+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-03-23T18:02:18.972954+00:00 heroku[web.1]: Process exited with status 143
2021-03-23T18:02:18.901699+00:00 app[web.1]: [2021-03-23 18:02:18] FATAL SignalException: SIGTERM
2021-03-23T18:02:18.901706+00:00 app[web.1]: 	/usr/lib/ruby/2.7.0/webrick/server.rb:170:in `select'
2021-03-23T18:02:18.901706+00:00 app[web.1]: 	/usr/lib/ruby/2.7.0/webrick/server.rb:170:in `block in start'
2021-03-23T18:02:18.901707+00:00 app[web.1]: 	/usr/lib/ruby/2.7.0/webrick/server.rb:32:in `start'
2021-03-23T18:02:18.901707+00:00 app[web.1]: 	/usr/lib/ruby/2.7.0/webrick/server.rb:157:in `start'
2021-03-23T18:02:18.901708+00:00 app[web.1]: 	-e:1:in `<main>'
2021-03-23T18:02:18.901836+00:00 app[web.1]: [2021-03-23 18:02:18] INFO  going to shutdown ...
2021-03-23T18:02:18.901938+00:00 app[web.1]: [2021-03-23 18:02:18] INFO  WEBrick::HTTPServer#start done.
2021-03-23T18:02:18.905921+00:00 app[web.1]: Terminated
2021-03-23T18:02:18.906149+00:00 app[web.1]: bin/minecraft: line 1: kill: (23) - No such process
2021-03-23T18:02:18.906154+00:00 app[web.1]: bin/minecraft: line 1: kill: (25) - No such process
2021-03-23T18:02:18.906155+00:00 app[web.1]: bin/minecraft: line 1: kill: (25) - No such process
2021-03-23T18:02:18.906157+00:00 app[web.1]: bin/minecraft: line 1: kill: (66) - No such process
```
This is my error, please help me !

**Comment by TheBotlyNoob** [comment]
Do you have enough Dyno hours? (You can check them [Here](https://help.heroku.com/FRHZA2YG/how-do-i-monitor-my-free-dyno-hours-quota)!)
