### ISSUE TITLE
Can't create a server

### ISSUE THREAD

**Issue by Hoffmano** [jkutner/heroku-buildpack-minecraft#82]
Repo files:
- eula.txt
`eula=true`
- requirements.txt
`s3cmd` 
- server.properties
  ```properties
  #Minecraft server properties
  #Mon Apr 20 14:07:49 UTC 2020
  online-mode=false
  enable-query=true
  ```

Details:
- Version 1.18.1
- Ngrok endpoint created successfully

Logs:
```yml
2022-06-19T17:33:54.882513+00:00 heroku[web.1]: Restarting
2022-06-19T17:33:54.884516+00:00 heroku[web.1]: State changed from up to starting
2022-06-19T17:33:55.560002+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2022-06-19T17:33:55.682733+00:00 app[web.1]: [2022-06-19 17:33:55] FATAL SignalException: SIGTERM
2022-06-19T17:33:55.682752+00:00 app[web.1]: 	/usr/lib/ruby/2.7.0/webrick/server.rb:170:in `select'
2022-06-19T17:33:55.682752+00:00 app[web.1]: 	/usr/lib/ruby/2.7.0/webrick/server.rb:170:in `block in start'
2022-06-19T17:33:55.682753+00:00 app[web.1]: 	/usr/lib/ruby/2.7.0/webrick/server.rb:32:in `start'
2022-06-19T17:33:55.682753+00:00 app[web.1]: 	/usr/lib/ruby/2.7.0/webrick/server.rb:157:in `start'
2022-06-19T17:33:55.682754+00:00 app[web.1]: 	-e:1:in `<main>'
2022-06-19T17:33:55.683104+00:00 app[web.1]: [2022-06-19 17:33:55] INFO  going to shutdown ...
2022-06-19T17:33:55.683125+00:00 app[web.1]: [2022-06-19 17:33:55] INFO  WEBrick::HTTPServer#start done.
2022-06-19T17:33:55.687156+00:00 app[web.1]: Terminated
2022-06-19T17:33:55.687287+00:00 app[web.1]: bin/minecraft: line 1: kill: (49) - No such process
2022-06-19T17:33:55.687296+00:00 app[web.1]: bin/minecraft: line 1: kill: (51) - No such process
2022-06-19T17:33:55.687305+00:00 app[web.1]: bin/minecraft: line 1: kill: (51) - No such process
2022-06-19T17:33:55.687315+00:00 app[web.1]: bin/minecraft: line 1: kill: (109) - No such process
2022-06-19T17:33:55.809429+00:00 heroku[web.1]: Process exited with status 143
2022-06-19T17:33:59.851921+00:00 heroku[web.1]: Starting process with command `bin/minecraft`
2022-06-19T17:34:00.539609+00:00 app[web.1]: Create a Procfile to customize the command used to run this process: https://devcenter.heroku.com/articles/procfile
2022-06-19T17:34:01.344312+00:00 app[web.1]: [heroku-exec] Starting
2022-06-19T17:34:01.374408+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2022-06-19T17:34:01.399997+00:00 app[web.1]: Starting ngrok...
2022-06-19T17:34:01.400337+00:00 app[web.1]: Starting sync...
2022-06-19T17:34:01.408310+00:00 app[web.1]: Starting: minecraft 25566
2022-06-19T17:34:01.645009+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=info msg="no configuration paths supplied"
2022-06-19T17:34:01.645038+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=info msg="ignoring default config path, could not stat it" path=/app/.ngrok2/ngrok.yml err="stat /app/.ngrok2/ngrok.yml: no such file or directory"
2022-06-19T17:34:01.645496+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="ignoring manifest file with unhandled mimetype" name=glyphicons-halflings-regular.svg ext=.svg
2022-06-19T17:34:01.645507+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="ignoring manifest file with unhandled mimetype" name=vendor.svg ext=.svg
2022-06-19T17:34:01.645781+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="starting component" obj=app name="signal handler"
2022-06-19T17:34:01.645891+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="starting component" obj=app name=web
2022-06-19T17:34:01.645904+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040
2022-06-19T17:34:01.645925+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="starting component" obj=app name=updater
2022-06-19T17:34:01.645972+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="checking for updates periodically" obj=updater interval=6h0m0s
2022-06-19T17:34:01.645985+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="check for update" obj=updater
2022-06-19T17:34:01.646078+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="starting component" obj=app name="Tunnel session"
2022-06-19T17:34:01.714299+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="open stream" obj=csess id=13cad9d1689b reqtype=0 err=nil
2022-06-19T17:34:01.714898+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="encode request" obj=csess id=13cad9d1689b sid=3 req="&{Version:[2] ClientID: Extra:{OS:linux Arch:amd64 Authtoken:2AngpzvqE5tdTVeQ19freFGv1OD_4SxXTZzQQeXxmN58Usua3 Version:2.3.40 Hostname:tunnel.us.ngrok.com UserAgent:ngrok/2 Metadata: Cookie: HeartbeatInterval:10000000000 HeartbeatTolerance:15000000000 Fingerprint:0xc000284930 UpdateUnsupportedError:0xc000282210 StopUnsupportedError:0xc000282200 RestartUnsupportedError:0xc0002821f0}}" err=nil
2022-06-19T17:34:01.736964+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="decoded response" obj=csess id=13cad9d1689b sid=3 resp="&{Version:2 ClientID:c74520b53bef009fc1de8ca090f7e4e2 Error: Extra:{Version:prod Cookie:w0Xlf9iensxyhTRcb2cUbKGQT8jnwlET$OZZAC3d0xxaZ5Q4kMhRMdxlJs7Npwtj7e61QjSahjDUE30v37TfJN3ZrNMADVe80yUZhY6/6uRUbGdMDZ70oOUHC6h3hDlulVQBII6s7kwoltiD5gvlq853jRuP1g9U+RCHBI9oLjj+V+xmlcbthHPbie5Y9dZWSGVH3hDMJI+9sf6sULCKQTmIAIB0NanCLOeqmpi16JtmJpqXbNuw= AccountName:hoffman.devs@gmail.com SessionDuration:0 PlanName:Free}}" err=nil
2022-06-19T17:34:01.737006+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=info msg="tunnel session started" obj=tunnels.session
2022-06-19T17:34:01.737015+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=info msg="client session established" obj=csess id=c777e8dd4ff9
2022-06-19T17:34:01.737162+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="open stream" obj=csess id=13cad9d1689b clientid=c74520b53bef009fc1de8ca090f7e4e2 reqtype=1 err=nil
2022-06-19T17:34:01.737292+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="encode request" obj=csess id=13cad9d1689b clientid=c74520b53bef009fc1de8ca090f7e4e2 sid=7 req="&{ID: ClientID: Proto:tcp Opts:0xc00007f210 Extra:{Token: IPPolicyRef: Metadata:}}" err=nil
2022-06-19T17:34:01.764084+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="decoded response" obj=csess id=13cad9d1689b clientid=c74520b53bef009fc1de8ca090f7e4e2 sid=7 resp="&{ClientID:ae3115343fed567d9f6ec6eeef1e3cbc URL:tcp://8.tcp.ngrok.io:13180 Proto:tcp Opts:map[Addr:8.tcp.ngrok.io:13180 IPRestriction:<nil> ProxyProto:0] Error: Extra:{Token:ZrQOpI1VzvNsOk0Q5lacrCpEDLhrEHKe$D+cawVwJfccPQgrv7bbkazrVzYJmZuvlUcALAve/FAWvUsa4gB9ilEaQnqY6TH8cuWngd/oCrKR9SoScjk3da47e0KVsyooJFftX1XVpsm/PWeuNMA1oBKb3Mys7I3TKNRDZP0PXR5r3p7r7duuNRT6o/VD66/wnGJmewKyN2xZXjOz4gYzDaAvOP3LQfW80b6NChrVzutdJziO44K7jyvZyHw==}}" err=nil
2022-06-19T17:34:01.764240+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="start tunnel listen" obj=tunnels.session name=command_line proto=tcp opts=&{Addr:} err=nil
2022-06-19T17:34:01.764279+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=info msg="started tunnel" obj=tunnels name=command_line addr=//localhost:25566 url=tcp://8.tcp.ngrok.io:13180
2022-06-19T17:34:01.789966+00:00 app[web.1]: t=2022-06-19T17:34:01+0000 lvl=dbug msg="no update available" obj=updater
2022-06-19T17:34:02.422290+00:00 app[web.1]: Tailing log
2022-06-19T17:34:02.424803+00:00 app[web.1]:         at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
2022-06-19T17:34:02.424804+00:00 app[web.1]:         at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2022-06-19T17:34:02.424804+00:00 app[web.1]:         at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2022-06-19T17:34:02.424805+00:00 app[web.1]:         at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2022-06-19T17:34:02.424805+00:00 app[web.1]:         at java.security.AccessController.doPrivileged(Native Method)
2022-06-19T17:34:02.424805+00:00 app[web.1]:         at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2022-06-19T17:34:02.424805+00:00 app[web.1]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2022-06-19T17:34:02.424806+00:00 app[web.1]:         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2022-06-19T17:34:02.424806+00:00 app[web.1]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2022-06-19T17:34:02.424807+00:00 app[web.1]:         at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
2022-06-19T17:34:02.578755+00:00 app[web.1]: [2022-06-19 17:34:02] INFO  WEBrick 1.6.0
2022-06-19T17:34:02.578764+00:00 app[web.1]: [2022-06-19 17:34:02] INFO  ruby 2.7.0 (2019-12-25) [x86_64-linux-gnu]
2022-06-19T17:34:02.578954+00:00 app[web.1]: [2022-06-19 17:34:02] INFO  WEBrick::HTTPServer#start: pid=110 port=29721
2022-06-19T17:34:03.050758+00:00 heroku[web.1]: State changed from starting to up
2022-06-19T17:34:11.726836+00:00 app[web.1]: t=2022-06-19T17:34:11+0000 lvl=dbug msg="heartbeat received" obj=csess id=13cad9d1689b clientid=c74520b53bef009fc1de8ca090f7e4e2 latency_ms=11
```

Testing server
![image](https://user-images.githubusercontent.com/30511353/174493341-78e80cbb-0c45-4187-b318-33d77ba4b006.png)
- Is not possible to connect on game too

If any other information is relevant, please, make a request

**Comment by VasyaYovbak** [comment]
same (

**Comment by proXDhiya** [comment]
same issue here
